module.exports = {
    "index":1,
    "menu":[
        {
            "name":"表单复合组件",
            "lists":[
                {
                    "href":"\/module\/turn",
                    "router":/(^\/module\/turn$)|(^\/module$)/,
                    "file":"module/turn",
                    "name":"开关、锁定",
                    "is-curr":false,
                    "data":{}
                },
                {
                    "href":"\/module\/progress",
                    "router":/^\/module\/progress$/,
                    "file":"module/progress",
                    "name":"进度条和刻度条",
                    "is-curr":false,
                    "data":{}
                },
                {
                    "href":"\/module\/upload",
                    "router":/^\/module\/upload$/,
                    "file":"module/upload",
                    "name":"异步上传组件",
                    "is-curr":false,
                    "data":{}
                },
                {
                    "href":"\/module\/pop-drop-tip",
                    "router":/^\/module\/pop-drop-tip$/,
                    "file":"module/pop-drop-tip",
                    "name":"输入框下拉提示",
                    "is-curr":false,
                    "data":{}
                },
                {
                    "href":"\/module\/node-tree",
                    "router":/^\/module\/node-tree$/,
                    "file":"module/node-tree",
                    "name":"节点树",
                    "is-curr":false,
                    "data":{}
                },
                {
                    "href":"\/module\/filter-menu",
                    "router":/^\/module\/filter-menu$/,
                    "file":"module/filter-menu",
                    "name":"筛选菜单",
                    "is-curr":false,
                    "data":{}
                }
            ]
        },
        {
            "name":"提示类组件",
            "lists":[
                {
                    "href":"\/module\/tip",
                    "router":/^\/module\/tip$/,
                    "file":"module/tip",
                    "name":"提示框",
                    "is-curr":false,
                    "data":{}
                },
                {
                    "href":"\/module\/pop-tip",
                    "router":/^\/module\/pop-tip$/,
                    "file":"module/pop-tip",
                    "name":"气泡提示框",
                    "is-curr":false,
                    "data":{}
                }
            ]
        },
        {
            "name":"模态弹窗",
            "lists":[
                {
                    "href":"\/module\/pop",
                    "router":/^\/module\/pop$/,
                    "file":"module/pop",
                    "name":"模态弹窗",
                    "is-curr":false,
                    "data":{}
                }
            ]
        }
    ]
}